sudo: required
dist: xenial

jobs:
  include:
    - os: linux
      arch: amd64

services:
  - docker

language: go

go:
  - 1.14.x

addons:
  apt:
    update: true

install:
  - pushd .
  - mkdir -p ${GOPATH}/src/k8s.io
  - cd ${GOPATH}/src/k8s.io
  - git clone -b kubernetes-1.17.0 https://github.com/kubernetes/code-generator
  - GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0
  - popd

before_script:
  - make update || travis_terminate 1;

script:
  - make test || travis_terminate 1;
  - make build && make image || travis_terminate 1;
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
     docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && make push-image || travis_terminate 1;
    fi

notifications:
  email:
    recipients:
    - mayank.patel@mayadata.io

branches:
  except:
    - /^*-v[0-9]/

